### ISSUE TITLE
Vehicle Spawning Issue

### ISSUE THREAD

**Issue by MannyOnBrazzers** [JericoFX/vehicleshopsByJericofx#1]
My players are running into some issues when they purchase the vehicle, sometimes it doesn't spawn, and if it does it's super scuffed and they can't enter the vehicle. Other issues where it would spawn, but then disappear. No errors. All dependencies are in, and SQL loaded perfectly

It works with GTA V regular vehicles but with custom models it has issues

**Comment by MannyOnBrazzers** [comment]
Update: if they purchase a regular GTA V model first, then the custom model would load fine

**Comment by MannyOnBrazzers** [comment]
Works on my local server fine, then when I throw it in my main server those issues occur

**Comment by JericoFX** [comment]
Maybe add a Wait when the resource spawn the vehicle, when i get home i will check it.

**Comment by JericoFX** [comment]
Can you tested now?

**Comment by colormeblind23** [comment]
I tested purchasing and it works perfectly

**Comment by JericoFX** [comment]
Thanks for testing!!
